[package]
name = "php-pdf"
version = "0.2.0"
edition = "2021"
authors = ["Ahmad Rosid <alahmadrosid@gmail.com>"]
license = "MIT"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
mupdf = "0.4.1"
phper = "0.12.0"
